image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/drndos/spoolman
persistence:
  spoolmandata:
    enabled: true
    mountPath: /home/app/.local/share/spoolman
portal:
  open:
    enabled: false
operator:
  verify:
    enabled: false
global:
  addTraefikAnnotations: false
podOptions:
  nodeSelector: {}
  topologySpreadConstraints: []
  defaultSpread: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8000
        protocol: tcp
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ENTRY: "{{ .Values.service.main.ports.main.port }}"
            PORT: "{{ .Values.service.main.ports.main.port }}"
            SCHEME: http
